diff_drive_controller:
  type: "diff_drive_controller/DiffDriveController"
  left_wheel_joint: "left_wheel2base_linkt"
  right_wheel_joint: "right_wheel2base_link"
  publish_rate: 50
  command:
    topic: cmd_vel

